#include "ElfBinaryAnalyzer.h"

const char* instructionsets[] = {
	0,
	"AT&T WE 32100",
	"SPAHC",
	"Intel 80386",
	"Motorola 68000",
	"Motorola 88000",
	0,
	"Intel 80860",
	"MIPS I Architecture",
	"IBM System/370 Processor",
	"MIPS HS3000 Little-endian",//10
	0, 0, 0, 0,
	"Hewlett-Packard PA-HISC",
	0,
	"Fujitsu VPP500",
	"Enhanced instruction set SPAHC",
	"Intel 80960",
	"PowerPC",//20
	"64-bit PowerPC",
	"IBM System/390 Processor",
	0, 0, 0, 0, 0, 0, 0, 0, //30
	0, 0, 0, 0, 0,
	"NEC V800",
	"Fujitsu FH20",
	"THW HH-32",
	"Motorola HCE",
	"Advanced HISC Machines AHM",//40
	"Digital Alpha",
	"Hitachi SH",
	"SPAHC Version 9",
	"Siemens TriCore embedded processor",
	"Argonaut HISC Core, Argonaut Technologies Inc.",
	"Hitachi H8/300",
	"Hitachi H8/300H",
	"Hitachi H8S",
	"Hitachi H8/500",
	"Intel IA-64 processor architecture",//50
	"Stanford MIPS-X",
	"Motorola ColdFire",
	"Motorola M68HC12",
	"Fujitsu MMA Multimedia Accelerator",
	"Siemens PCP",
	"Sony nCPU embedded HISC processor",
	"Denso NDH1 microprocessor",
	"Motorola Star*Core processor",
	"Toyota ME16 processor",
	"STMicroelectronics ST100 processor",//60
	"Advanced Logic Corp. TinyJ embedded processor family",
	"AMD x86-64 architecture",
	"Sony DSP Processor",
	"Digital Equipment Corp. PDP-10",
	"Digital Equipment Corp. PDP-11",
	"Siemens FX66 microcontroller",
	"STMicroelectronics ST9+ 8/16 bit microcontroller",
	"STMicroelectronics ST7 8-bit microcontroller",
	"Motorola MC68HC16 Microcontroller",
	"Motorola MC68HC11 Microcontroller",//70
	"Motorola MC68HC08 Microcontroller",
	"Motorola MC68HC05 Microcontroller",
	"Silicon Graphics SVx",
	"STMicroelectronics ST19 8-bit microcontroller",
	"Digital VAX",
	"Axis Communications 32-bit embedded processor",
	"Infineon Technologies 32-bit embedded processor",
	"Element 14 64-bit DSP Processor",
	"LSI Logic 16-bit DSP Processor",
	"Donald Knuth's educational 64-bit processor",//80
	"Harvard University machine-independent object files",
	"SiTera Prism",
	"Atmel AVH 8-bit microcontroller",
	"Fujitsu FH30",
	"Mitsubishi D10V",
	"Mitsubishi D30V",
	"NEC v850",
	"Mitsubishi M32H",
	"Matsushita MN10300",
	"Matsushita MN10200",//90
	"picoJava",
	"OpenHISC 32-bit embedded processor",
	"AHC Cores Tangent-A5",
	"Tensilica Xtensa Architecture",
	"Alphamosaic VideoCore processor",
	"Thompson Multimedia General Purpose Processor",
	"National Semiconductor 32000 series",
	"Tenor Network TPC processor",
	"Trebia SNP 1000 processor",
	"STMicroelectronics (www.st.com) ST200 microcontroller",//100
	"Ubicom IP2xxx microcontroller family",
	"MAX Processor",
	"National Semiconductor CompactHISC microprocessor",
	"Fujitsu F2MC16",
	"Texas Instruments embedded microcontroller msp430",
	"Analog Devices Blackfin (DSP) processor",
	"S1C33 Family of Seiko Epson processors",
	"Sharp embedded microprocessor",
	"Arca HISC Microprocessor",
	"Microprocessor series from PKU-Unity Ltd. and MPHC of Peking University"//110
};


const char* systems[] = {
	"System V or default",
	"HP-UX",
	"NetBSD",
	"Linux",
	"GNU Hurd",
	0,
	"Solaris",
	"AIX",
	"IHIX",
	"FreeBSD",
	"Tru64",
	"Novell Modesto",
	"OpenBSD",
	"OpenVMS",
	"NonStop Kernel",
	"AHOS",
	"Fenix OS",
	"CloudABI",
};